logo: logo.jpg # add logo name
title: Arash Rezaei
description: This is the Personal Website for Arash Rezaei
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arashrezaeimusic.com" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: header.png # add banner video. Add your video file to the folder video
banner-desc: Arash Rezaei
banner-title: آرش رضایی

# Author settings
author-pic: face.jpg # your photo
author-name: Arash Rezaei # your name
about-author: Arash Rezaei is an Iranian music producer and Guitar player from Tehran, Iran currently located at Valencia, Spain. Previous works include working with different Metal, Rock, Hiphop and Electronic music artists. # about author
email: arashrezaeiproduction@gmail.com # your email
phone: +34-677169686 # your pnone number
website: https://arashrezaeimusic.com # you website

# Social link
instagram_url: https://www.instagram.com/arashrezaeimusic/
soundcloud_url: https://soundcloud.com/arash-rezaei-786121242
youtube_url: https://www.youtube.com/channel/UCNxlHuWxdUt-rCs1k-X5nvQ
github_url: https://github.com/sndevil
linkedin_url: https://www.linkedin.com/in/arash-rezaei-76040a176/
spotify_url: https://open.spotify.com/artist/0jViUNb1uh1dDNLYMqq4Zs?si=Q49oLpoVTletdDr_I4qNJw

# Disqus
discus_identifier: mr-brown # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
